---
apps: 
  - artifactId: rentman
    groupId: com.itteddy
    cleanStart: true
    repo: git@github.com:itteddy/rentman.git
    version: master
    dockerfile: src/main/docker/Dockerfile.multiarch
    artifact: target/quarkus-app
    type: folder
    buildVersion: "1.0.3"
    nextVersion:
    subfolder: 
    mavenrepo: https://admin:password@reposilite.awon.lan/releases
    arch:
      - linux-amd64
      - linux-arm-v7
    registries: 
      - registry.awon.lan
  - artifactId: teddycast
    groupId: com.itteddy
    cleanStart: true
    repo: git@github.com:itteddy/teddycast.git
    version: master
    dockerfile: src/main/docker/Dockerfile.multiarch
    artifact: target/quarkus-app
    type: folder
    buildVersion: "1.0.2"
    nextVersion:
    subfolder: 
    mavenrepo: https://admin:password@reposilite.awon.lan/releases
    arch:
      - linux-amd64
      - linux-arm-v7
    registries: 
      - registry.awon.lan

prom:
  node:
    - "cipi.lan:9100"
    - "bbee.lan:9100"
    - "awon.lan:9100"
    - "fuja.lan:9100"
    - "fujb.lan:9100"
    - "hpel.lan:9100"
    - "asus.lan:9100"

  cadvisor:
    - "cadvisor.cipi.lan"
    - "cadvisor.bbee.lan"
    - "cadvisor.awon.lan"
    - "cadvisor.fuja.lan"
    - "cadvisor.fujb.lan"
    - "cadvisor.hpel.lan"
    - "cadvisor.asus.lan"
  traefik:
    - "cipi.lan:8080"
    - "bbee.lan:8080"
    - "awon.lan:8080"
    - "fuja.lan:8080"
    - "fujb.lan:8080"
    - "hpel.lan:8080"
    - "asus.lan:8080"
  o11y:
    - "grafana.awon.lan"
  artemis:
    - artemis-console.awon.lan
  camelquarkus:
    - rentman.awon.lan
    - teddycast.awon.lan
  camelspring:
    - spring.awon.lan
  kafka:
    - kafka-metrics.awon.lan
    - kafkaexporter.awon.lan
  zookeeper:
    - zookeeper-metrics.awon.lan