---
appconfig:


  traefik: 
    ip: 172.18.0.43
    image: docker.io/traefik:2.9.5


    declare_hostname: false
    appstate: "{{ global_appstate }}"
    recreate: "{{ global_recreate }}"
    purge: "{{ global_purge }}"
    exec_as_user: 0
    exec_as_group: 0
    config_folder: "{{ config_folder_default }}"
    data_folder: "{{ data_folder_default }}"
    ports: 
      - "80:80"
      - "443:443"
      # - "8080:8080"

  portainer: 
    ip: 172.18.0.40
    image: portainer/portainer-ce:2.16.2

    declare_hostname: false
    appstate: "{{ global_appstate }}"
    recreate: "{{ global_recreate }}"
    purge: "{{ global_purge }}"
    exec_as_user: 0
    exec_as_group: 0
    config_folder: "{{ config_folder_default }}"
    data_folder: "{{ data_folder_default }}"
    ports: 


  cadvisor: 
    ip: 172.18.0.77
    image: gcr.io/cadvisor/cadvisor:v0.46.0
    
    declare_hostname: false
    appstate: "{{ global_appstate }}"
    recreate: "{{ global_recreate }}"
    purge: "{{ global_purge }}"
    exec_as_user: 0
    exec_as_group: 0
    config_folder: "{{ config_folder_default }}"
    data_folder: "{{ data_folder_default }}"
    ports: 


  grafana: 
    ip: 172.18.0.71
    image: grafana/grafana:9.3.1

    declare_hostname: false
    appstate: "{{ global_appstate }}"
    recreate: "{{ global_recreate }}"
    purge: "{{ global_purge }}"
    exec_as_user: 1000
    exec_as_group: 1000
    config_folder: "{{ config_folder_default }}"
    data_folder: "{{ data_folder_default }}"
    ports: 

    prom_url: http://prometheus:9090

  plex: 
    image: linuxserver/plex:1.30.0

    declare_hostname: false
    appstate: "{{ global_appstate }}"
    recreate: "{{ global_recreate }}"
    purge: "{{ global_purge }}"
    exec_as_user: 1000
    exec_as_group: 1000
    config_folder: "{{ config_folder_default }}"
    data_folder: "{{ data_folder_default }}"
    ports: 
    

apps: 
  rentman:
    artifactId: rentman
    groupId: com.itteddy
    cleanStart: true
    repo: git@github.com:itteddy/rentman.git
    version: master
    dockerfile: src/main/docker/Dockerfile.multiarch
    artifact: target/quarkus-app
    type: folder
    buildVersion: "1.0.3"
    nextVersion:
    subfolder: 
    mavenrepo: https://admin:password@reposilite.awon.lan/releases
    arch:
      - linux-amd64
      - linux-arm-v7
    registries: 
      - registry.awon.lan
  teddycast:
    artifactId: teddycast
    groupId: com.itteddy
    cleanStart: true
    repo: git@github.com:itteddy/teddycast.git
    version: master
    dockerfile: src/main/docker/Dockerfile.multiarch
    artifact: target/quarkus-app
    type: folder
    buildVersion: "1.0.3"
    nextVersion:
    subfolder: 
    mavenrepo: https://admin:password@reposilite.awon.lan/releases
    arch:
      - linux-amd64
      - linux-arm-v7
    registries: 
      - registry.awon.lan

prom:
  node:
    - "cipi.lan:9100"
    - "bbee.lan:9100"
    - "awon.lan:9100"
    - "fuja.lan:9100"
    - "fujb.lan:9100"
    - "hpel.lan:9100"
    - "asus.lan:9100"

  cadvisor:
    - "cadvisor.cipi.lan"
    - "cadvisor.bbee.lan"
    - "cadvisor.awon.lan"
    - "cadvisor.fuja.lan"
    - "cadvisor.fujb.lan"
    - "cadvisor.hpel.lan"
    - "cadvisor.asus.lan"
  traefik:
    - "cipi.lan:8080"
    - "bbee.lan:8080"
    - "awon.lan:8080"
    - "fuja.lan:8080"
    - "fujb.lan:8080"
    - "hpel.lan:8080"
    - "asus.lan:8080"
  o11y:
    - "grafana.awon.lan"
  artemis:
    - artemis-console.awon.lan
  camelquarkus:
    - rentman.awon.lan
    - teddycast.awon.lan
  camelspring:
    - spring.awon.lan
  kafka:
    - kafka-metrics.awon.lan
    - kafkaexporter.awon.lan
  zookeeper:
    - zookeeper-metrics.awon.lan