---
- name: tls root ca copy
  hosts:
    - mvp
  tasks:
    - name: install
      include_role:
        name: cloud-native-appdev-lab-role
        tasks_from: tls-distribute-ca-from-local

- name: tls create
  hosts:
    - mvp
  tasks:
    - name: install
      include_role:
        name: cloud-native-appdev-lab-role
        tasks_from: tls-setup