---
- name: tls root ca copy
  hosts:
    - selected
  tasks:
    - name: install
      include_role:
        name: cloud-native-appdev-lab-role
        tasks_from: tls-distribute-ca-from-local

- name: tls create
  hosts:
    - hpel.lan
  tasks:
    - name: install
      include_role:
        name: cloud-native-appdev-lab-role
        tasks_from: tls-setup