---
- name: build java bytecode on x86 machines
  hosts:
    - awon.lan
  serial: 1
  tasks:
    - include_role:
        name: cloud-native-appdev-lab-role
        tasks_from: cicd-java-build

- name: build & push containers to registry
  hosts:
    - awon.lan
    - bbee.lan
  tasks:
    - include_role:
        name: cloud-native-appdev-lab-role
        tasks_from: cicd-container-push

- name: push multi arch manifest
  hosts:
    - awon.lan
  tasks:
    - include_role:
        name: cloud-native-appdev-lab-role
        tasks_from: cicd-container-manifest