---
- name: multi-arch-apps
  hosts:
    - awon.lan
  serial: 1
  vars:
    apps: 
      # - artifactId: rentman
      #   groupId: com.itteddy
      #   cleanStart: true
      #   repo: git@github.com:itteddy/rentman.git
      #   version: master
      #   dockerfile: src/main/docker/Dockerfile.multiarch
      #   buildVersion: "1.0.1"
      #   nextVersion:
      #   subfolder: 
      #   registries: 
      #     - registry.awon.lan
      - artifactId: teddycast
        groupId: com.itteddy
        cleanStart: true
        repo: git@github.com:itteddy/teddycast.git
        version: master
        dockerfile: src/main/docker/Dockerfile.multiarch
        buildVersion: "1.0.1"
        nextVersion:
        subfolder: 
        registries: 
          - registry.awon.lan
  tasks:
    - include_role:
        name: cloud-native-appdev-lab-role
        tasks_from: cicd-java-build
    - include_role:
        name: cloud-native-appdev-lab-role
        tasks_from: cicd-container-push