- name: mvp
  hosts:
    - mvp
  vars:
    appstate: started
    recreate: true
  tasks:
    - include_role:
        name: cloud-native-appdev-lab-role
        tasks_from: app-{{ rolesvar }}
      loop:
        - cadvisor
      loop_control:
        loop_var: rolesvar