# - name: kube
#   hosts:
#     - kube
#   vars:
#     appstate: started
#     recreate: true
#   tasks:
#     - include_role:
#         name: cloud-native-appdev-lab-role
#         tasks_from: app-{{ rolesvar }}
#       loop:
#         - traefik
#         - portainer
#         - cadvisor
#       loop_control:
#         loop_var: rolesvar

- name: tls root ca copy
  hosts:
    - kube
  tasks:
    - name: install
      include_role:
        name: cloud-native-appdev-lab-role
        tasks_from: tls-distribute-ca-from-local

- name: tls create
  hosts:
    - kube
  tasks:
    - name: install
      include_role:
        name: cloud-native-appdev-lab-role
        tasks_from: tls-setup