---
- name: mvp
  hosts:
    - fujb.lan
  vars:
    global_recreate: true
    global_appstate: started
    global_purge: true
  tasks:
    - include_role:
        name: cloud-native-appdev-lab-role
        tasks_from: app-{{ rolesvar }}
      loop:
        - traefik
        - portainer
        - cadvisor
      loop_control:
        loop_var: rolesvar