# - name: tls root ca copy
#   hosts:
#     - asus.lan
#   tasks:
#     - name: install
#       include_role:
#         name: cloud-native-appdev-lab-role
#         tasks_from: tls-distribute-ca-from-local

# - name: tls create
#   hosts:
#     - asus.lan
#   tasks:
#     - name: install
#       include_role:
#         name: cloud-native-appdev-lab-role
#         tasks_from: tls-setup

# - name: asus.lan
#   hosts:
#     - asus.lan
#   vars:
#     appstate: started
#     recreate: true
#   tasks:
#     - include_role:
#         name: cloud-native-appdev-lab-role
#         tasks_from: app-{{ rolesvar }}
#       loop:
#         - traefik
#         - portainer
#         - cadvisor
#       loop_control:
#         loop_var: rolesvar

- name: awon
  hosts:
    - awon.lan
  vars:
    appstate: started
    recreate: true
    purge: false
  tasks:
    - include_role:
        name: cloud-native-appdev-lab-role
        tasks_from: app-{{ rolesvar }}
      loop:
        - prometheus
      loop_control:
        loop_var: rolesvar
